-- =============================================================
-- Migration: comprobantes_anulacion_as_flag_and_audit_triggers
-- Fase: comprobantes-anulacion-refactor tasks 2.2-2.4
-- =============================================================
--
-- §11.6 CLAUDE.md: GIN trigram indexes (contactos_razonSocial_trgm_idx,
-- contactos_nombreComercial_trgm_idx) were present in the Prisma migrate diff
-- output as DROP INDEX — those lines are intentionally OMITTED here because
-- they are raw-SQL objects declared in migration 20260424020927_fase_1_4_contactos
-- and must be preserved. Same applies to pg_trgm extension.
--
-- Part A: Schema changes (generated by prisma migrate diff, hand-edited per §11.6)
-- Part B: Raw SQL objects (comprobantes_audit table + trigger function + triggers)

-- ============================================================
-- PART A: Schema changes
-- ============================================================

-- AlterEnum: drop ANULADO from EstadoComprobante (rename/create/cast/drop pattern
-- because Postgres has no ALTER TYPE ... DROP VALUE).
-- The partial unique index on comprobante_documento_fisico (comprobante_documento_fisico_unique_contabilizado)
-- uses WHERE comprobanteEstado = 'CONTABILIZADO'::"EstadoComprobante" — it must be dropped BEFORE
-- the type rename because Postgres holds the old type reference in the index definition, causing
-- operator mismatch errors during ALTER COLUMN. Recreated after the rename.
-- See: §11.6 CLAUDE.md — this raw-SQL index is in the known-good list and will be restored below.
DROP INDEX IF EXISTS "comprobante_documento_fisico_unique_contabilizado";

CREATE TYPE "EstadoComprobante_new" AS ENUM ('BORRADOR', 'CONTABILIZADO', 'BLOQUEADO');
ALTER TABLE "public"."comprobantes" ALTER COLUMN "estado" DROP DEFAULT;
ALTER TABLE "comprobantes" ALTER COLUMN "estado" TYPE "EstadoComprobante_new" USING ("estado"::text::"EstadoComprobante_new");
ALTER TABLE "comprobante_documento_fisico" ALTER COLUMN "comprobanteEstado" TYPE "EstadoComprobante_new" USING ("comprobanteEstado"::text::"EstadoComprobante_new");
ALTER TYPE "EstadoComprobante" RENAME TO "EstadoComprobante_old";
ALTER TYPE "EstadoComprobante_new" RENAME TO "EstadoComprobante";
DROP TYPE "public"."EstadoComprobante_old";
ALTER TABLE "comprobantes" ALTER COLUMN "estado" SET DEFAULT 'BORRADOR';

-- Restore the partial unique index with the new type (§11.6 known-good raw SQL object).
CREATE UNIQUE INDEX "comprobante_documento_fisico_unique_contabilizado"
  ON "comprobante_documento_fisico"("documentoFisicoId")
  WHERE "comprobanteEstado" = 'CONTABILIZADO'::"EstadoComprobante";

-- DropForeignKey
ALTER TABLE "comprobantes" DROP CONSTRAINT "comprobantes_anulaAId_fkey";

-- DropForeignKey (ComprobanteAuditoria → Comprobante + PeriodoFiscalReopening)
ALTER TABLE "comprobantes_auditoria" DROP CONSTRAINT "comprobantes_auditoria_comprobanteId_fkey";
ALTER TABLE "comprobantes_auditoria" DROP CONSTRAINT "comprobantes_auditoria_reaperturaId_fkey";

-- DropIndex (reversión 1:1 unique)
DROP INDEX "comprobantes_anulaAId_key";

-- NOTE: DROP INDEX for contactos_nombreComercial_trgm_idx and contactos_razonSocial_trgm_idx
-- were present in prisma migrate diff output but are intentionally excluded here.
-- These are raw-SQL GIN trigram indexes from migration 20260424020927_fase_1_4_contactos
-- and must survive (§11.6 CLAUDE.md protocol).

-- AlterTable comprobantes: drop old anulacion fields, add flag-based fields
ALTER TABLE "comprobantes"
  DROP COLUMN "anulaAId",
  DROP COLUMN "anuladoEn",
  ADD COLUMN "anulado"        BOOLEAN      NOT NULL DEFAULT false,
  ADD COLUMN "fechaAnulacion" TIMESTAMPTZ(3);

-- DropTable: old audit table (replaced by raw comprobantes_audit + triggers)
DROP TABLE "comprobantes_auditoria";

-- DropEnum: AccionAuditoriaComprobante (no longer used)
DROP TYPE "AccionAuditoriaComprobante";

-- CreateIndex: anulados por periodo
CREATE INDEX "comprobantes_organizationId_periodoFiscalId_anulado_idx"
  ON "comprobantes"("organizationId", "periodoFiscalId", "anulado");

-- ============================================================
-- PART B: Raw SQL objects — comprobantes_audit infrastructure
-- ============================================================
--
-- These objects are intentionally outside Prisma schema. They are Postgres-native
-- audit triggers that capture full row snapshots (OLD + NEW) with session context.
-- See CLAUDE.md §4.3 and §4.7: triggers, not service code, so even direct SQL
-- UPDATE/DELETE in the DB is traced.

-- Audit table: one row per INSERT/UPDATE/DELETE on comprobantes or lineas_comprobante.
CREATE TABLE IF NOT EXISTS comprobantes_audit (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tabla            TEXT        NOT NULL,               -- 'comprobantes' | 'lineas_comprobante'
  operacion        TEXT        NOT NULL,               -- 'INSERT' | 'UPDATE' | 'DELETE'
  comprobante_id   UUID        NOT NULL,               -- siempre el comprobante padre
  organization_id  UUID        NOT NULL,
  usuario_id       TEXT,                               -- app.audit_user_id session var (nullable: migrations directas)
  motivo           TEXT,                               -- app.audit_motivo
  durante_reapertura BOOLEAN   NOT NULL DEFAULT false, -- app.audit_during_reopening
  reapertura_id    UUID,                               -- app.audit_reapertura_id
  datos_antes      JSONB,                              -- OLD row (NULL en INSERT)
  datos_despues    JSONB,                              -- NEW row (NULL en DELETE)
  ts               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS comprobantes_audit_comprobante_id_ts_idx
  ON comprobantes_audit(comprobante_id, ts);

CREATE INDEX IF NOT EXISTS comprobantes_audit_organization_id_ts_idx
  ON comprobantes_audit(organization_id, ts);

-- Trigger function: called after INSERT/UPDATE/DELETE on comprobantes and lineas_comprobante.
-- Reads session vars set by AuditedTransactionRunner (task 3.x) via set_config().
CREATE OR REPLACE FUNCTION trg_comprobantes_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_comprobante_id UUID;
  v_organization_id UUID;
BEGIN
  -- Resolve comprobante_id and organization_id from the affected row.
  IF TG_TABLE_NAME = 'comprobantes' THEN
    IF TG_OP = 'DELETE' THEN
      v_comprobante_id  := OLD.id;
      v_organization_id := OLD."organizationId";
    ELSE
      v_comprobante_id  := NEW.id;
      v_organization_id := NEW."organizationId";
    END IF;
  ELSE -- lineas_comprobante
    IF TG_OP = 'DELETE' THEN
      v_comprobante_id  := OLD."comprobanteId";
      v_organization_id := OLD."organizationId";
    ELSE
      v_comprobante_id  := NEW."comprobanteId";
      v_organization_id := NEW."organizationId";
    END IF;
  END IF;

  INSERT INTO comprobantes_audit (
    tabla,
    operacion,
    comprobante_id,
    organization_id,
    usuario_id,
    motivo,
    durante_reapertura,
    reapertura_id,
    datos_antes,
    datos_despues
  ) VALUES (
    TG_TABLE_NAME,
    TG_OP,
    v_comprobante_id,
    v_organization_id,
    current_setting('app.audit_user_id',   true),
    current_setting('app.audit_motivo',    true),
    COALESCE(current_setting('app.audit_during_reopening', true)::boolean, false),
    NULLIF(current_setting('app.audit_reapertura_id', true), '')::uuid,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
    CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END;
$$;

-- Trigger on comprobantes
DROP TRIGGER IF EXISTS trg_audit_comprobantes ON comprobantes;
CREATE TRIGGER trg_audit_comprobantes
  AFTER INSERT OR UPDATE OR DELETE ON comprobantes
  FOR EACH ROW EXECUTE FUNCTION trg_comprobantes_audit();

-- Trigger on lineas_comprobante
DROP TRIGGER IF EXISTS trg_audit_lineas_comprobante ON lineas_comprobante;
CREATE TRIGGER trg_audit_lineas_comprobante
  AFTER INSERT OR UPDATE OR DELETE ON lineas_comprobante
  FOR EACH ROW EXECUTE FUNCTION trg_comprobantes_audit();
